CREATE  TABLE BMW_DEALERS (
    DEALER_CODE      VARCHAR2(20) PRIMARY KEY,
    DEALER_NAME      VARCHAR2(100) NOT NULL,
    REGION           VARCHAR2(50),
    COUNTRY          VARCHAR2(50)
);

CREATE   TABLE BMW_MODELS (
    MODEL_CODE       VARCHAR2(20) PRIMARY KEY,
    BRAND            VARCHAR2(20) CHECK (BRAND IN ('BMW', 'MINI')),
    MODEL_NAME       VARCHAR2(100) NOT NULL,
    TRIM             VARCHAR2(50),
    SEGMENT          VARCHAR2(50)
);

CREATE   TABLE BMW_SALES_CALENDAR (
    DATE_VALUE       DATE PRIMARY KEY,
    YEAR_NUM         NUMBER,
    MONTH_NUM        NUMBER,
    MONTH_NAME       VARCHAR2(20),
    BLACKOUT_FLAG    NUMBER(1) DEFAULT 0 CHECK (BLACKOUT_FLAG IN (0, 1)),
    CONSTRAINT CK_CAL_DATE_ONLY CHECK (DATE_VALUE = TRUNC(DATE_VALUE))
);


INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D001', 'Parkway BMW', 'Northeast', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D001');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D002', 'Hudson MINI', 'Northeast', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D002');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D003', 'Lakeside Motors', 'Midwest', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D003');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D004', 'Prairie Auto', 'Midwest', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D004');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D005', 'Sunbelt Motors', 'South', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D005');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D006', 'Gulf Coast Auto', 'South', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D006');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D007', 'Canyon Cars', 'West', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D007');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D008', 'Pacific BMW', 'West', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D008');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D009', 'Liberty Autos', 'Northeast', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D009');

INSERT INTO BMW_DEALERS (DEALER_CODE, DEALER_NAME, REGION, COUNTRY)
SELECT 'D010', 'Frontier MINI', 'West', 'USA' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_DEALERS WHERE DEALER_CODE = 'D010');

-- Seed BMW/MINI model rows
INSERT INTO BMW_MODELS (MODEL_CODE, BRAND, MODEL_NAME, TRIM, SEGMENT)
SELECT 'MINI-Ctrymn-S4', 'MINI', 'Countryman', 'S ALL4', 'Crossover' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_MODELS WHERE MODEL_CODE = 'MINI-Ctrymn-S4');

INSERT INTO BMW_MODELS (MODEL_CODE, BRAND, MODEL_NAME, TRIM, SEGMENT)
SELECT 'BMW-X3-30i', 'BMW', 'X3', 'xDrive30i', 'SUV' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_MODELS WHERE MODEL_CODE = 'BMW-X3-30i');

INSERT INTO BMW_MODELS (MODEL_CODE, BRAND, MODEL_NAME, TRIM, SEGMENT)
SELECT 'BMW-330i', 'BMW', '3 Series', '330i', 'Sedan' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_MODELS WHERE MODEL_CODE = 'BMW-330i');

INSERT INTO BMW_MODELS (MODEL_CODE, BRAND, MODEL_NAME, TRIM, SEGMENT)
SELECT 'MINI-CooperS', 'MINI', 'Cooper S', 'S', 'Compact' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM BMW_MODELS WHERE MODEL_CODE = 'MINI-CooperS');

Populate the sales calendar once; skip dates already present if the script is rerun.
DECLARE
    v_start_date DATE := DATE '2010-01-01';
    v_end_date   DATE := DATE '2035-12-31';
BEGIN
    FOR d IN (
        SELECT v_start_date + LEVEL - 1 AS dt
        FROM dual
        CONNECT BY v_start_date + LEVEL - 1 <= v_end_date
    )
    LOOP
        INSERT INTO BMW_SALES_CALENDAR
            (DATE_VALUE, YEAR_NUM, MONTH_NUM, MONTH_NAME, BLACKOUT_FLAG)
        SELECT
            d.dt,
            EXTRACT(YEAR FROM d.dt),
            EXTRACT(MONTH FROM d.dt),
            TO_CHAR(d.dt, 'Month'),
            0
        FROM dual
        WHERE NOT EXISTS (
            SELECT 1
            FROM BMW_SALES_CALENDAR c
            WHERE c.DATE_VALUE = d.dt
        );
    END LOOP;
END;











